### ISSUE TITLE
join became ambiguous after updating to tdplyr 17.00.00.01 and dbplyr 2.1.1

### ISSUE THREAD

**Issue by yjian69** [Teradata/tdplyr#4] opened 2021-11-08 23:04 UTC
hi Community, 

I'm a user of tdplyr 17.00.00.00 and dbplyr 1.4.4 before and my data table joins work fine, however, after I updated to tdplyr 17.00.00.01 and dbplyr 2.1.1, part of my join gives the following error.

Error in new_result(connection@ptr, statement, immediate) : 
  nanodbc/nanodbc.cpp:1412: 42S02: [Teradata][ODBC Teradata Driver][Teradata Database](-3809)Column 'Article_Id' is ambiguous. 
Timing stopped at: 0.97 0.02 1.36

Below is my code:

sales_1 <- sales %>% 
  left_join(., when_where, by =c("Site_Id" = "Site_Id", 
                                 "Posted_Dt" = "Calendar_Dt"))%>%
  inner_join(., art_mch_hier , by = c("Article_Id" = "Article_ID"))

It joins fine with "Site_Id" and "Posted_Dt = Calendar_Dt", however, "Article_Id" = "Article_ID" errored out. is there any update on case sensitivity? i cannot change the column names since i'm pulling data directly from database. Please kindly help.

Thanks in advance!

**Comment by jerisalan** [comment] 2021-11-22 23:19
Hey @yjian69, we have not changed the underlying behavior of the joins in the new release and I believe the change was made in the dbplyr package (https://github.com/tidyverse/dbplyr/releases/tag/v2.0.0). 
Whenever it comes to resolving ambiguous column names with respect to any database, it is usually because an alias for the table is not specified/used and the database cannot resolve it when the same column name appears on both tables which are being joined. 
What I would recommend is try posting the issue there in dbplyr repository with a simple minimal reproducible example and then should be able to point out the fix for the same.

**Comment by lcl-teradata** [comment] 2023-07-20 09:02
Closing this issue as the issue is at the dbplyr end.

**Closed as completed by lcl-teradata** 2023-07-20 09:02 UTC
